server:
    port: 8080

spring:
    profiles:
        active: prod
    data:
        cassandra:
            contactPoints: localhost
            protocolVersion: V2
            compression: LZ4
            keyspaceName: jhipstertoken

    mail:
        baseUrl: http://localhost:8080

    thymeleaf:
        mode: XHTML
        cache: true

metrics:
    jmx.enabled: true
    spark:
        enabled: false
        host: localhost
        port: 9999
    graphite:
        enabled: false
        host: localhost
        port: 2003
        prefix: jhipstertoken


